services:
  - type: web
    name: marketing-chat
    env: docker
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:$PORT app:app
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketing_chat_p
          property: connectionString
databases:
  - name: marketing_chat_p
    plan: basic-256mb   # <-- fais correspondre au plan actuel de la DB
